import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const gilroy = localFont({
  src: [
    {
      path: "../fonts/Gilroy-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Gilroy-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-gilroy",
});

export const metadata: Metadata = {
  title: "CREO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gilroy.variable}`}>{children}</body>
    </html>
  );
}
